version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      my_network:
        ipv4_address: ${POSTGRES_IP}
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - postgresql_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    networks:
      my_network:
        ipv4_address: ${PGADMIN_IP}
    ports:
      - "5050:5050"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgresql_data:
  pgadmin_data:

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET} # Define the IP address range for the network
